import os
import openai

def generate_instructions(script, openai_key, engine="davinci", max_tokens=150):
  """

  Creates a list of instructions based on a video script using the GPT-3 model of OpenAI.
  
  Args:
    script:
      String containing the video script.
    openai_key:
      Secret API Key. 
    engine:
      The name of the GPT-3 engine. (Default: "davinci")
    max_tokens:
      The maximum number of tokens to be generated. (Default: 150)
  
  Returns:
    response: 
      String containing the list of instructions generated by GPT-3.

  """
  prompt ="###\n"\
  "Text to extract instructions from:\n"\
  "\n"\
  "Hello, today I want to show you how you can configure a template button the notion. So first I created an empty page, give it a title of test page. Then we want to search for the templates button. If we have it and selected now we can configure our own template button. First we will give it a name, we'll name it add a new to do block. And then every block we want to have a header and the to do list. So we're This is the block that actually appears when we are pressing a button. So first we want header. We'll select all section header, name it's pool, block number, and then we could select the number and then we will add a to do list. Then we click on Close. So now every time we click on this add new to do block the new heading the new to do list will appear. This is how template buttons work. If we want to we configured which is press the settings and then we could add this we could probably list it for clothes. Every time we press on the button. This new block with the toggle editor that will appeal to very much\n"\
  "\n"\
  "\n"\
  "Are step-by-step instructions available: Yes\n"\
  "Instructions:\n"\
  "1. Create empty page in Notion\n"\
  "2. Search for template button\n"\
  "3. Select and configure template button\n"\
  "4. Give template button a name\n"\
  "5. Add new block\n"\
  "6. Click on close\n"\
  "7. For configuration, click on settings\n"\
  "###\n"\
  "Text to extract instructions from:\n"\
  "\n"\
  "Hello, today I want to show you how you can clear your browser cache and cookies in Google Chrome. First you select More in the top right of the window. You will find it under these three dots. Then we go under More tools and select Clear browsing data. At the top, you can choose a time range. To delete everything, we will select All time. Now, you can select additional things to delete like Cookies and other site data or Cached images and files. Just check the respective boxes. After having selected everything you want to delete, you click on Clear data. Voila, now your cache is cleared and the cookies are deleted.\n"\
  "\n"\
  "\n"\
  "Are step-by-step instructions available: Yes\n"\
  "Instructions:\n"\
  "1. Select More in the top right of the window\n"\
  "2. Select More tools\n"\
  "3. Select Clear browsing data\n"\
  "4. Select All time\n"\
  "5. Select additional things to delete\n"\
  "6. Click on Clear data\n"\
  "###\n"\
  "Text to extract instructions from:\n"\
  "\n"\
  "Hello everyone, today I want to talk to you about the charter of open AI. So one important aspect are broadly distributed benefits. So we want artificial intelligence for the benefit of all. While not enabling users of AI that may harm humanity. We also want to minimize conflicts of interests among stakeholders that could compromise our goal. Apart from that, we want long term safety. So we want you to research required to make artificial intelligence safe. And if a value aligned project reaches the goal First, we are planning on teaming up with them in order to avoid the rights. In order to achieve that, we also need technical leadership. So openly I must be on the cutting edge of AI capabilities, and also lead with the pre products. Those should, in turn be used according to our chart. Lastly, we have a cooperative orientation. So we want to actively cooperate with other research and policy institutions to create a global community working together to address API's global challenges, and provide public goods like source code.\n"\
  "\n"\
  "\n"\
  "Are step-by-step instructions available: No\n"\
  "###\n"\
  "Text to extract instructions from:\n"\
  "\n" + script + "\n"\
  "\n"\
  "\n"\
  "Are step-by-step instructions available:"

  openai.api_key = openai_key

  response = openai.Completion.create(
    engine=engine,
    prompt = prompt,
    temperature=0.0,
    max_tokens=max_tokens,
    top_p=0.0,
    frequency_penalty=0.0,
    presence_penalty=0.0,
    stop=["###"]
  )["choices"][0]["text"]

  if response[0:3] == " No":
    response = "No step-by-step instructions available"
  else:
    response = response[5:]

  
  return response